# Generated by Django 2.1 on 2018-09-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='avaliacao',
            field=models.IntegerField(verbose_name='Avaliação'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_pub',
            field=models.DateField(verbose_name='Data da Publicação'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='paginas',
            field=models.IntegerField(verbose_name='Páginas'),
        ),
    ]
