# Generated by Django 2.1 on 2018-09-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_auto_20180927_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='avaliacao',
            field=models.FloatField(verbose_name='Avaliação'),
        ),
    ]
