# Generated by Django 2.1.1 on 2018-10-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20180927_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='livros',
        ),
    ]
