# Generated by Django 2.1.1 on 2018-10-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_remove_loja_livros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='idade',
            field=models.IntegerField(verbose_name='Idade'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='quantidade_de_clientes',
            field=models.PositiveIntegerField(verbose_name='QTD de clientes'),
        ),
    ]
